version: '3.8'

services:
    mysqldb:
        image: mysql:5.7
        restart: unless-stopped
        container_name: brecho_mysql
        env_file:
            - ./.env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_TCP_PORT: ${MYSQL_DOCKER_PORT}
        ports:
            - "${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}"
        expose:
            - "${MYSQL_DOCKER_PORT}"
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

    api:
        depends_on:
            mysqldb: 
                condition: service_healthy
        build: .
        image: backend
        restart: unless-stopped
        env_file: ./.env
        environment:
            - MYSQL_HOST=mysqldb
            - MYSQL_LOCAL_PORT=${MYSQL_DOCKER_PORT}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USERNAME=${MYSQL_USERNAME}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - ${PYTHON_LOCAL_PORT}:${PYTHON_LOCAL_PORT}
        stdin_open: true
        tty: true
