"""delete analyse

Revision ID: 2d3beb9ba8b5
Revises: 8ec989a71dd6
Create Date: 2025-07-19 09:02:13.390650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2d3beb9ba8b5'
down_revision: Union[str, None] = '8ec989a71dd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_analyse')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_analyse',
    sa.Column('checkout_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('address_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('shipping_fee', mysql.DECIMAL(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['tbl_address.address_id'], name=op.f('tbl_analyse_ibfk_1')),
    sa.ForeignKeyConstraint(['checkout_id'], ['tbl_checkout.checkout_id'], name=op.f('tbl_analyse_ibfk_2')),
    sa.PrimaryKeyConstraint('checkout_id', 'address_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
