"""add new tables

Revision ID: 8ec989a71dd6
Revises: 49fe31781fe5
Create Date: 2025-07-09 12:47:18.891180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec989a71dd6'
down_revision: Union[str, None] = '49fe31781fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_checkout',
    sa.Column('checkout_id', sa.Integer(), nullable=False),
    sa.Column('promotion', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['tbl_client.client_id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('checkout_id')
    )
    op.create_table('tbl_analyse',
    sa.Column('checkout_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('shipping_fee', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['tbl_address.address_id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['checkout_id'], ['tbl_checkout.checkout_id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('checkout_id', 'address_id')
    )
    op.create_table('tbl_cart_want',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('want_type', sa.Enum('cart', 'wishlist', name='wanttype'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['tbl_client.client_id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['tbl_product.product_id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('product_id', 'client_id')
    )
    op.create_table('tbl_generate',
    sa.Column('checkout_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['checkout_id'], ['tbl_checkout.checkout_id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['tbl_product.product_id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('checkout_id', 'product_id')
    )
    op.create_table('tbl_order_payment',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('order_updated_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.Enum('credit_card', 'debit_card', 'boleto', 'pix', name='paymentmethod'), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('order_tracking', sa.Enum('shipped', 'in_transit', 'delivered', 'returned', name='tracking'), nullable=True),
    sa.Column('checkout_id', sa.Integer(), nullable=False),
    sa.Column('order_status', sa.Enum('pending', 'paid', 'shipped', 'delivered', 'cancelled', 'expired', name='orderstatus'), server_default='pending', nullable=False),
    sa.ForeignKeyConstraint(['checkout_id'], ['tbl_checkout.checkout_id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_table('tbl_boleto',
    sa.Column('boleto_id', sa.Integer(), nullable=False),
    sa.Column('boleto_bar_code', sa.String(length=255), nullable=False),
    sa.Column('boleto_expiry_date', sa.Date(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['tbl_order_payment.order_id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('boleto_id'),
    sa.UniqueConstraint('boleto_bar_code')
    )
    op.create_table('tbl_card',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=20), nullable=False),
    sa.Column('card_expiry_date', sa.Date(), nullable=False),
    sa.Column('card_holder_name', sa.String(length=100), nullable=False),
    sa.Column('card_holder_national_code', sa.String(length=20), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['tbl_order_payment.order_id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_table('tbl_pix',
    sa.Column('pix_id', sa.Integer(), nullable=False),
    sa.Column('pix_key', sa.String(length=255), nullable=False),
    sa.Column('pix_expiry_date', sa.DateTime(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['tbl_order_payment.order_id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('pix_id'),
    sa.UniqueConstraint('pix_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_pix')
    op.drop_table('tbl_card')
    op.drop_table('tbl_boleto')
    op.drop_table('tbl_order_payment')
    op.drop_table('tbl_generate')
    op.drop_table('tbl_cart_want')
    op.drop_table('tbl_analyse')
    op.drop_table('tbl_checkout')
    # ### end Alembic commands ###
