"""add new models

Revision ID: b87615fe33d9
Revises: f6c8df4c6505
Create Date: 2025-07-09 11:25:55.689452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b87615fe33d9'
down_revision: Union[str, None] = 'f6c8df4c6505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('user_nickname', sa.String(length=255), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('user_password', sa.String(length=255), nullable=False),
    sa.Column('user_phone_country_code', sa.String(length=10), nullable=False),
    sa.Column('user_phone_state_code', sa.String(length=10), nullable=False),
    sa.Column('user_phone_number', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_nickname')
    )
    op.drop_index(op.f('user_email'), table_name='users')
    op.drop_index(op.f('user_nickname'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_nickname', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('user_nickname'), 'users', ['user_nickname'], unique=True)
    op.create_index(op.f('user_email'), 'users', ['user_email'], unique=True)
    op.drop_table('tbl_user')
    # ### end Alembic commands ###
