name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      ACCESS_TOKEN_EXPIRE_MINUTES=30
      MYSQL_LOCAL_PORT: ${{ secrets.MYSQL_LOCAL_PORT }}
      MYSQL_DOCKER_PORT: ${{ secrets.MYSQL_DOCKER_PORT }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

    steps:
      - name: Copia os arquivos do repositório
        uses: actions/checkout@v4

      - name: Instalar o python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar o poetry
        run: pipx install poetry

      - name: Instalar dependências
        run: cd backend && poetry install

      - name: Executar testes
        run: cd backend && poetry run task lint && poetry run task format && poetry run task test